cleanup: remove seat management
ansible/ansible-ai-connect-service pull request #1173
Opened 2024-07-03 12:47 UTC by pb82

Jira Issue: https://issues.redhat.com/browse/AAP-25245

## Description

Removes the seat check logic and relevant unit tests.

## Testing

1. Run the wisdom service locally and try to log in with an AAP licensed user
2. It should succeed

### Scenarios tested

as described above

## Production deployment

- [x] This code change is ready for production on its own
- [ ] This code change requires the following considerations before going to production:

2024-07-03 15:00 UTC, goneri requested changes

2024-07-03 15:00 UTC, goneri commented on ansible_ai_connect/users/authz_checker.py
> -    def rh_org_has_subscription(self, organization_id: int) -> bool:
We still need this method to know if the Org has an AAP subscription.

2024-07-04 12:36 UTC, pb82 commented
@goneri thanks for the review. In that case, I guess we should remove the `check` method of the AMSCheck and CIAMCheck since they are no longer used?

2024-07-04 12:40 UTC, goneri commented
That sounds reasonable to me, even if we still use a tiny part the module.

2024-07-04 14:47 UTC, pb82 commented
Closing this to split it up into multiple PRs

2024-07-04 14:47 UTC, closed without merging