PR to fix ansible-ai-connect-service: Cross-site Scripting (XSS) in serialize-javascript
ansible/ansible-ai-connect-service pull request #1353
Opened 2024-10-17 14:31 UTC by justjais

Jira Issue: <https://issues.redhat.com/browse/AAP-31381>

## Description

PR to fix ansible-ai-connect-service: Cross-site Scripting (XSS) in serialize-javascript

## Testing

### Steps to test
1. Pull down the PR
2. Run `npm install` and node packages should install as expected w/o failures
3. Run `npm audit fix` to verify if there's any vulnerabilities, currently there's 0.

### Scenarios tested

NA

## Production deployment

- [ ] This code change is ready for production on its own
- [ ] This code change requires the following considerations before going to production:

2024-10-17 18:35 UTC, jameswnl commented
we probably have to fix it in the `package.json`?

2024-10-29 05:51 UTC, manstis commented
Upgrade to PF5 isn't easy.

You'll need to bump the version of Ansible UI framework too (to one using PF5) and fix the fallout too.

2024-10-29 06:05 UTC, justjais commented
@manstis yea, this isn't a 1 story point and straight CVE fix, for fixing this patternfly needs to be updated to ^5.1 coz npm update updates ansible-ui-framework package which is in turn dependent over patternfly ^5.1, and the fallout needs to be resolved as you mentioned.

I'll bring this up during today's scrum and how to move forward with the issue.

2024-11-22 12:30 UTC, manstis requested changes
The styling is now, unfortunately, wrong:

**AAP-31381**
![AAP-31381](https://github.com/user-attachments/assets/bbe8ad76-ca7d-4334-aeae-efbbdf16c77b)

**Original**
![original](https://github.com/user-attachments/assets/0b394c57-68d2-4798-bb33-296ffb921b17)

Furthermore the "kebab" menu (top left corner) does not work properly.

It should collapse the left-hand-side navigation menu.

2024-11-22 12:30 UTC, manstis commented on ansible_ai_connect_admin_portal/src/SingleInlineEdit.tsx
> +            // onChange={(value, event) => props.onChange?.(value)}
Do we need this comment?

2024-11-22 12:30 UTC, manstis commented on ansible_ai_connect_admin_portal/src/__tests__/AppHeader.test.tsx
> -
You seem to have remove the test for logging out?

2024-11-28 05:11 UTC, manstis approved these changes
The icon/text alignment in the left-hand-side menu still is not correct; but the kebab menu works now :smile_cat: 

![image](https://github.com/user-attachments/assets/a60aa6c0-fb8b-4a89-96d9-06863a7fdb6b)

Approving; but I suggest a follow-up JIRA to fix the alignment be made.

2024-11-28 06:43 UTC, justjais commented
@manstis thanks for the review, and giving green light to the PR. Also, I've opened a bug jira: https://issues.redhat.com/browse/AAP-36777, to address the alignment issue.

2024-11-28 06:43 UTC, merged