Update login.html
ansible/ansible-ai-connect-service pull request #1446
Opened 2024-12-06 18:47 UTC by omaciel

Updated deprecated documentation URL to use the official commercial documentation URL.

Jira Issue: [<https://issues.redhat.com/browse/AAP-NNNN>](https://issues.redhat.com/browse/AAP-33000)

## Description
Updated the documentation URL for the login page to point to the official commercial documentation URL.

## Testing

### Steps to test
1. Pull down the PR
2. Run the service
3. Ensure that before you login, clicking the Documentation link takes you to the commercial documentation URL on access.redhat.com (and not docs.ai...)

### Scenarios tested
Visual verification only.

## Production deployment
- [x] This code change is ready for production on its own
- [ ] This code change requires the following considerations before going to production:

2024-12-06 22:23 UTC, TamiTakamiya requested changes
@omaciel LoginView code needs to be updated to set `documentation_url` like:

```python
class LoginView(auth_views.LoginView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["deployment_mode"] = settings.DEPLOYMENT_MODE
        context["project_name"] = settings.ANSIBLE_AI_PROJECT_NAME
        context["aap_api_provider_name"] = settings.AAP_API_PROVIDER_NAME
        context["documentation_url"] = settings.COMMERCIAL_DOCUMENTATION_URL # <===
        return context
```
Would you update the PR to include that line?

2024-12-07 00:46 UTC, omaciel commented
Thanks @TamiTakamiya I had missed that.

2024-12-07 02:54 UTC, TamiTakamiya approved these changes
lgtm

2024-12-07 15:26 UTC, omaciel commented
The attached video shows the current behavior of clicking the Login button followed by clicking the Documentation link which incorrectly takes the user to https://docs.ai.ansible.redhat.com/  AND the corrected issue where the user is taken to https://docs.redhat.com/en/documentation/red_hat_ansible_lightspeed_with_ibm_watsonx_code_assistant/2.x_latest/html/red_hat_ansible_lightspeed_with_ibm_watsonx_code_assistant_user_guide/index

![AAP-33000](https://github.com/user-attachments/assets/56a9da8f-c0ee-41df-8035-2c5f68993623)

2024-12-07 15:27 UTC, merged