disable tech preview in wisdom-service
ansible/ansible-ai-connect-service pull request #789
Opened 2024-01-22 21:39 UTC by goneri

Jira Issue: <https://issues.redhat.com/browse/AAP-19427>

## Description

Introduce the new `ANSIBLE_AI_ENABLE_TECH_PREVIEW` configuration key
that can be use to enable or disable the Tech Preview mode.
By default, the key is enable since the Tech Preview is still supported.

The commit also do the following changes when the Tech Preview is disabled:

- Block access to non seated users to the Completion and Attribution end points
- Return specific error to the VSCode extension when a non-seated user get blocked
- Display clear messages regarding the status of the user

## Testing

The PR is fully unit-tested, you can also set `ANSIBLE_AI_ENABLE_TECH_PREVIEW` to `False` to reproduce a situation where the Tech Preview is disabled.

## Production deployment

- [x] This code change is ready for production on its own

2024-01-25 20:02 UTC, TamiTakamiya reviewed
I left two comments. Would you take a look?

2024-01-25 20:35 UTC, robinbobbitt requested changes
Looking good! I've left a few comments. An additional gap to call out is that new unseated users are still getting the tech preview terms of service presented when tech preview is off. Please take a look.

2024-01-26 21:41 UTC, robinbobbitt requested changes
@goneri please note my previous comment about tech preview terms still being presented. Thanks!

2024-01-31 20:23 UTC, manstis reviewed
A couple of minor comments.. they don't _break_ the PR; but may make nicer reading.

2024-01-31 20:39 UTC, manstis submitted a review, later dismissed
LGTM :+1:

2024-02-03 07:24 UTC, manstis submitted a review, later dismissed
LGTM 👍 

Is there a JIRA to remove the `user.community_terms_accepted` field (and all the `ANSIBLE_AI_ENABLE_TECH_PREVIEW` flag usage etc) when Tech Preview ends?

IDK if it'll be easier to track what needs refactoring now, as theses changes are added, than hunting for them later. Your choice 👍

2024-02-03 16:40 UTC, robinbobbitt requested changes
We are so close! Just one concern noted. Thanks @goneri !

2024-02-06 17:33 UTC, robinbobbitt requested changes

2024-02-06 19:46 UTC, robinbobbitt approved these changes

2024-02-06 19:49 UTC, merged