AAP-23914: Lightspeed Telemetry :: Populate FQCN information, even if post-processing is disabled
ansible/ansible-ai-connect-service pull request #996
Opened 2024-05-09 19:35 UTC by romartin

Jira Issue: <https://issues.redhat.com/browse/AAP-23914>

## Description
Since the post-processing being disabled by [1], on staging clusters, some telemetry evens are lacking the following information:
- schema1: completion event => missing tasks
- schema2: Recommendation Generated event => collection and module fields are empty

[1] https://github.com/ansible/ansible-wisdom-ops/commit/ce89fb48544e300dc55c9db6969bd06a8b363ba4

### Steps to test
- Disable ARI post-processing => ENABLE_ARI_POSTPROCESS=False
- Run the wisdom-service
- Infer
- Look at either completion event, from schema1, and _Recommendation Generated event, from schema2, both are lacking information, as described above.

### Scenarios tested
Tested local against staging Segment account, when both post-processing enabled and disabled.

## Production deployment

- [x] This code change is ready for production on its own
- [ ] This code change requires the following considerations before going to production:

2024-05-09 20:18 UTC, manstis reviewed
I see you've simply moved population of the `fqcn_module` outside of `ari_results` block. Fair enough. Makes sense. Shouldn't you however have a test so that the problematic scenario can be detected ongoing?

2024-05-10 05:22 UTC, manstis submitted a review, later dismissed
LGTM 👍

2024-05-10 18:52 UTC, robinbobbitt requested changes
Thanks Roger! Just a couple small comments.

2024-05-11 06:41 UTC, manstis approved these changes
LGTM 👍

2024-05-14 02:28 UTC, robinbobbitt approved these changes
LGTM! Thanks.

2024-05-14 12:16 UTC, merged